[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/api/products"
  to = "/.netlify/functions/products"
  status = 200
  force = true

[[redirects]]
  from = "/api/sales"
  to = "/.netlify/functions/sales"
  status = 200
  force = true

[[redirects]]
  from = "/api/settings"
  to = "/.netlify/functions/settings"
  status = 200
  force = true
